spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager?useUnicode=yes&characterEncoding=UTF-8
    username: taskmanager
    password: taskmanager
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
#  metrics:
#    export:
#      graphite:
#        host: localhost
#        port: 8008

management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: task-manager
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "metrics" ]

scoring:
  limit: 4
